# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.9

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/wupeicong/OS/elevator

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/wupeicong/OS/elevator

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/wupeicong/OS/elevator/CMakeFiles /home/wupeicong/OS/elevator/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/wupeicong/OS/elevator/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ele

# Build rule for target.
ele: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ele
.PHONY : ele

# fast build rule for target.
ele/fast:
	$(MAKE) -f CMakeFiles/ele.dir/build.make CMakeFiles/ele.dir/build
.PHONY : ele/fast

ele.o: ele.c.o

.PHONY : ele.o

# target to build an object file
ele.c.o:
	$(MAKE) -f CMakeFiles/ele.dir/build.make CMakeFiles/ele.dir/ele.c.o
.PHONY : ele.c.o

ele.i: ele.c.i

.PHONY : ele.i

# target to preprocess a source file
ele.c.i:
	$(MAKE) -f CMakeFiles/ele.dir/build.make CMakeFiles/ele.dir/ele.c.i
.PHONY : ele.c.i

ele.s: ele.c.s

.PHONY : ele.s

# target to generate assembly for a file
ele.c.s:
	$(MAKE) -f CMakeFiles/ele.dir/build.make CMakeFiles/ele.dir/ele.c.s
.PHONY : ele.c.s

elevator_ctrl_ui.o: elevator_ctrl_ui.c.o

.PHONY : elevator_ctrl_ui.o

# target to build an object file
elevator_ctrl_ui.c.o:
	$(MAKE) -f CMakeFiles/ele.dir/build.make CMakeFiles/ele.dir/elevator_ctrl_ui.c.o
.PHONY : elevator_ctrl_ui.c.o

elevator_ctrl_ui.i: elevator_ctrl_ui.c.i

.PHONY : elevator_ctrl_ui.i

# target to preprocess a source file
elevator_ctrl_ui.c.i:
	$(MAKE) -f CMakeFiles/ele.dir/build.make CMakeFiles/ele.dir/elevator_ctrl_ui.c.i
.PHONY : elevator_ctrl_ui.c.i

elevator_ctrl_ui.s: elevator_ctrl_ui.c.s

.PHONY : elevator_ctrl_ui.s

# target to generate assembly for a file
elevator_ctrl_ui.c.s:
	$(MAKE) -f CMakeFiles/ele.dir/build.make CMakeFiles/ele.dir/elevator_ctrl_ui.c.s
.PHONY : elevator_ctrl_ui.c.s

floor_ui.o: floor_ui.c.o

.PHONY : floor_ui.o

# target to build an object file
floor_ui.c.o:
	$(MAKE) -f CMakeFiles/ele.dir/build.make CMakeFiles/ele.dir/floor_ui.c.o
.PHONY : floor_ui.c.o

floor_ui.i: floor_ui.c.i

.PHONY : floor_ui.i

# target to preprocess a source file
floor_ui.c.i:
	$(MAKE) -f CMakeFiles/ele.dir/build.make CMakeFiles/ele.dir/floor_ui.c.i
.PHONY : floor_ui.c.i

floor_ui.s: floor_ui.c.s

.PHONY : floor_ui.s

# target to generate assembly for a file
floor_ui.c.s:
	$(MAKE) -f CMakeFiles/ele.dir/build.make CMakeFiles/ele.dir/floor_ui.c.s
.PHONY : floor_ui.c.s

main.o: main.c.o

.PHONY : main.o

# target to build an object file
main.c.o:
	$(MAKE) -f CMakeFiles/ele.dir/build.make CMakeFiles/ele.dir/main.c.o
.PHONY : main.c.o

main.i: main.c.i

.PHONY : main.i

# target to preprocess a source file
main.c.i:
	$(MAKE) -f CMakeFiles/ele.dir/build.make CMakeFiles/ele.dir/main.c.i
.PHONY : main.c.i

main.s: main.c.s

.PHONY : main.s

# target to generate assembly for a file
main.c.s:
	$(MAKE) -f CMakeFiles/ele.dir/build.make CMakeFiles/ele.dir/main.c.s
.PHONY : main.c.s

pipe.o: pipe.c.o

.PHONY : pipe.o

# target to build an object file
pipe.c.o:
	$(MAKE) -f CMakeFiles/ele.dir/build.make CMakeFiles/ele.dir/pipe.c.o
.PHONY : pipe.c.o

pipe.i: pipe.c.i

.PHONY : pipe.i

# target to preprocess a source file
pipe.c.i:
	$(MAKE) -f CMakeFiles/ele.dir/build.make CMakeFiles/ele.dir/pipe.c.i
.PHONY : pipe.c.i

pipe.s: pipe.c.s

.PHONY : pipe.s

# target to generate assembly for a file
pipe.c.s:
	$(MAKE) -f CMakeFiles/ele.dir/build.make CMakeFiles/ele.dir/pipe.c.s
.PHONY : pipe.c.s

process.o: process.c.o

.PHONY : process.o

# target to build an object file
process.c.o:
	$(MAKE) -f CMakeFiles/ele.dir/build.make CMakeFiles/ele.dir/process.c.o
.PHONY : process.c.o

process.i: process.c.i

.PHONY : process.i

# target to preprocess a source file
process.c.i:
	$(MAKE) -f CMakeFiles/ele.dir/build.make CMakeFiles/ele.dir/process.c.i
.PHONY : process.c.i

process.s: process.c.s

.PHONY : process.s

# target to generate assembly for a file
process.c.s:
	$(MAKE) -f CMakeFiles/ele.dir/build.make CMakeFiles/ele.dir/process.c.s
.PHONY : process.c.s

schedule.o: schedule.c.o

.PHONY : schedule.o

# target to build an object file
schedule.c.o:
	$(MAKE) -f CMakeFiles/ele.dir/build.make CMakeFiles/ele.dir/schedule.c.o
.PHONY : schedule.c.o

schedule.i: schedule.c.i

.PHONY : schedule.i

# target to preprocess a source file
schedule.c.i:
	$(MAKE) -f CMakeFiles/ele.dir/build.make CMakeFiles/ele.dir/schedule.c.i
.PHONY : schedule.c.i

schedule.s: schedule.c.s

.PHONY : schedule.s

# target to generate assembly for a file
schedule.c.s:
	$(MAKE) -f CMakeFiles/ele.dir/build.make CMakeFiles/ele.dir/schedule.c.s
.PHONY : schedule.c.s

smemory.o: smemory.c.o

.PHONY : smemory.o

# target to build an object file
smemory.c.o:
	$(MAKE) -f CMakeFiles/ele.dir/build.make CMakeFiles/ele.dir/smemory.c.o
.PHONY : smemory.c.o

smemory.i: smemory.c.i

.PHONY : smemory.i

# target to preprocess a source file
smemory.c.i:
	$(MAKE) -f CMakeFiles/ele.dir/build.make CMakeFiles/ele.dir/smemory.c.i
.PHONY : smemory.c.i

smemory.s: smemory.c.s

.PHONY : smemory.s

# target to generate assembly for a file
smemory.c.s:
	$(MAKE) -f CMakeFiles/ele.dir/build.make CMakeFiles/ele.dir/smemory.c.s
.PHONY : smemory.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... ele"
	@echo "... edit_cache"
	@echo "... ele.o"
	@echo "... ele.i"
	@echo "... ele.s"
	@echo "... elevator_ctrl_ui.o"
	@echo "... elevator_ctrl_ui.i"
	@echo "... elevator_ctrl_ui.s"
	@echo "... floor_ui.o"
	@echo "... floor_ui.i"
	@echo "... floor_ui.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... pipe.o"
	@echo "... pipe.i"
	@echo "... pipe.s"
	@echo "... process.o"
	@echo "... process.i"
	@echo "... process.s"
	@echo "... schedule.o"
	@echo "... schedule.i"
	@echo "... schedule.s"
	@echo "... smemory.o"
	@echo "... smemory.i"
	@echo "... smemory.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

